version: "3.8"

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: "SENHADOBANCO"
    volumes:
      - ../install/postgresql:/docker-entrypoint-initdb.d:ro
      - db:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5432:5432
    labels:
      - traefik.enable=false
    networks:
      pgd:
        aliases:
          - postgres_sgd

networks:
  pgd:
    external: true
    name: pgd

volumes:
  db:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /opt/dados/sgd/postgres